name: Deploy Package to Production
"on":
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "A release version to deploy, e.g. v1.0.0"
        required: true
        default: "v1.0.0"

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: refs/tags/${{ github.event.inputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --force

      - name: Setup .env
        run: |
          echo "WALLET_CONNECT_PROJECT_ID=${{ secrets.WALLET_CONNECT_PROJECT_ID }}" > .env
          echo "ANKR_TOKEN=${{ secrets.ANKR_TOKEN }}" >> .env
          echo "SCREENING_API_URL=${{ secrets.SCREENING_API_URL }}" >> .env

      - name: Build
        run: |
          npm run generate
      
      - name: Reorganize Files
        run: |
          mkdir -p dist/bridge
          mv dist/_nuxt dist/bridge/_nuxt

      - name: Deploy to Production
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DAPP_WALLET_V2 }}"
          projectId: zksync-dapp-wallet-v2
          channelID: live
